#pragma once

#include <cstdint>

// Forward declarations (automatically generated)
class WindissectOpaque;
namespace Microsoft { namespace WRL { class Details; } } 
namespace Microsoft { namespace WRL { namespace Wrappers { class Details; } } } 
namespace Windows { namespace Internal { class Details; } } 
namespace Windows { namespace Internal { class PlatformExtensions; } } 
namespace Windows { namespace Internal { class QuickActions; } } 
class ActivityData; class CActivatedEventArgsBase; class CActivatedEventArgsWithPrelaunchAndViewIdBase; class CActivatedEventArgsWithViewIdBase; class CLaunchActivatedEventArgs; class CThreadRefTaker; class CloseHandle; class DesktopShellQuickActionsLogging; class Destroy; class EventRegistrationToken; class FEATURE_ERROR; class FEATURE_LOGGED_TRAITS; class FEATURE_STATE_CHANGE_SUBSCRIPTION__; class HINSTANCE__; class HKEY__; class HSTRING__; class IActivationFactory; class IClassFactory; class IInspectable; class IStream; class IUnknown; class IWeakReference; class RegCloseKey; class ReleaseSRWLockExclusive; class ReleaseSRWLockShared; class WilFailureReport; class WilFailureReportInformation; class WindowsDeleteString; class _CONTEXT; class _EVENT_FILTER_DESCRIPTOR; class _EXCEPTION_RECORD; class _GUID; class _RO_REGISTRATION_COOKIE; class _RTL_RUN_ONCE; class _RTL_SRWLOCK; class _TP_CALLBACK_INSTANCE; class _TP_TIMER; class _TP_WAIT; class _TP_WORK; class _TlgReflectorTag_Param0IsProviderType; class __WIL_RTL_FEATURE_USAGE_DATA; class __WIL__WNF_STATE_NAME; class _tlgProvider_t; class _tlgWrapSz; class _tlgWrapperByRef; class _tlgWrapperByVal; class exception; class lambda_052e919cc0e5399df76dff3972c0cac1; class lambda_082e526f59ffa603266044e9a30d7707; class lambda_098e22c106ed5c3c624220f41ad87182; class lambda_0d85958e25c6d23f40d8d7cc280bee0e; class lambda_0fcbc6dba7235f3f169237fa2387b8f2; class lambda_32772c4dbf9c5d3c682e3b3561ad4a19; class lambda_384deeafcf0d9374b9205e96279984ff; class lambda_3d1cf41359bed25a2eb427649bdebd4e; class lambda_43189107f8967ec93ea4c123df277c6c; class lambda_46bcd20538be875b834c828d87b6132d; class lambda_4849719eb6573c95f59938315036521d; class lambda_59558555a4d0fe468583914261d1d770; class lambda_7192802f9b3849fb3827ffaa2f586c56; class lambda_72983ddf05b902877d71aefc2ac98ae8; class lambda_7d21a7f8ed4692e5fdd5369ac3cb8df4; class lambda_82a98796e3570e8a170b667da9621eb6; class lambda_8bbd59964544f4264e1ae68760a3b1e0; class lambda_90bb8bc73e4d8f6ae1715cda4fe8533c; class lambda_920a655ce1b83f90dc4c61d5b8822386; class lambda_9e97c7f183c14d5d1fd709d10b418904; class lambda_a495222dfaf81692749e6b037e3727e7; class lambda_a5fafce0f86356b0f6580c2356136fd2; class lambda_b8a26addd5fc6ba3f09898777136a4cc; class lambda_b9fa1a293e755b81c35fd74826879719; class lambda_c07c12682fcf4217da772c12d3170edc; class lambda_c388ceb6e21ed47becc1ba6cbfc11075; class lambda_ce564f7947f0b9d2442134a983f8f3c7; class lambda_dfdb6b7448c71a564849bf18b5889f8d; class lambda_e43905c5ce0b9f4f0283e5d1e74d69ea; class lambda_f2b70d3afd6994c9269874b0f6d65a30; class lambda_f39176db2056a91e205b47dba90506b1; class lambda_f481c443581c17c1cb49a9f6266cb47b; class lambda_f62ed7851a87f032f90c4deb87f3b899; class permission; class thunk; class type_info; class wil_FeatureState; class wil_details_FeatureReportingCache; class wil_details_FeatureStateCache; class wil_details_FeatureUsageSRUM; 
namespace Concurrency { class scheduler_interface; class scheduler_ptr; class task; class task_completion_event; class task_continuation_context; class task_options; } 
namespace Concurrency { namespace details { class _ContextCallback; class _ContinuationTaskHandleBase; class _ExceptionHolder; class _Task_completion_event_impl; class _Task_impl; class _Task_impl_base; class _TypeSelectorNoAsync; } } 
namespace Custom { class _AutoDeleteChore; class _TaskCollectionImpl; } 
namespace Microsoft { namespace WRL { class ActivationFactory; class CloakedIid; class ComPtr; class Details; class EventSource; class FtmBase; class InvokeModeOptions; class RuntimeClassFlags; class SimpleSealedActivationFactory; class WeakRef; } } 
namespace Microsoft { namespace WRL { namespace Wrappers { class Details; class HString; class HStringReference; class SRWLock; } } } 
namespace QuickActionsTelemetry { class InitializeQuickAction; class InvokingQuickSetting; } 
namespace SystemSettings { namespace DataModel { class ISettingItem; class ISettingsEnvironmentChangedHandler; class ISettingsEnvironmentDatabase; } } 
namespace Windows { } 
namespace Windows { namespace ApplicationModel { namespace Activation { class ILaunchActivatedEventArgs; class ILaunchActivatedEventArgs2; class ISplashScreen; class ITileActivatedInfo; class MultiviewActivationProperties; } } } 
namespace Windows { namespace ApplicationModel { namespace Activation { namespace Private { class IApplicationActivationProperties; class IApplicationActivationStatics; } } } } 
namespace Windows { namespace Foundation { namespace Collections { class Detail; } } } 
namespace Windows { namespace Foundation { namespace Collections { namespace Internal { class VectorChangedEventArgs; class detail; } } } } 
namespace Windows { namespace Internal { class Details; class GitEventSource; class GitPtr; class PlatformExtensions; class QuickActions; class String; class StringReference; } } 
namespace Windows { namespace Internal { namespace ApplicationModel { namespace WindowManagement { class WindowId; } } } } 
namespace Windows { namespace Internal { namespace ComTaskPool { class CTaskWrapper; } } } 
namespace Windows { namespace Internal { namespace Foundation { namespace Contracts { class IActivationFactoryContractRedirectorContext; } } } } 
namespace Windows { namespace System { class ILauncherStatics; class ILauncherStatics4; class IUser; class User; } } 
namespace Windows { namespace UI { namespace ViewManagement { class IActivationViewSwitcher; } } } 
namespace XWinRT { class ComLock; class IntVersionTag; class InterfaceEquals; class InterfaceLifetimeTraits; class SerializingLockPolicy; } 
namespace XWinRT { namespace detail { class AcquireRead; class AcquireWrite; class AtomicUpdates; class GitStorageType; class LockHolder; class ReentrancyGuard; } } 
namespace pplx { class cancellation_token; class cancellation_token_registration; class cancellation_token_source; class invalid_operation; } 
namespace pplx { namespace details { class CancellationTokenRegistration_TaskProc; class _CancellationTokenRegistration; class _CancellationTokenState; class _Chore; class _RefCounterBase; class _Scheduler_Param; class _UnrealizedChore; class critical_section_impl; class event_impl; class windows_scheduler; } } 
namespace std { class _Callable_obj; class _Func_base; class _Func_class; class _Func_impl; class _List_node; class _Nil; class _Nonscalar_ptr_iterator_tag; class _Ref_count_base; class _Simple_types; class _Tree_const_iterator; class _Tree_iterator; class _Tree_node; class _Tree_simple_types; class _Tree_val; class _Vector_iterator; class _Vector_val; class _Wrap_alloc; class allocator; class bad_alloc; class bad_function_call; class basic_string; class char_traits; class error_code; class error_condition; class exception_ptr; class function; class integral_constant; class length_error; class list; class logic_error; class nothrow_t; class nullptr_t; class out_of_range; class pair; class shared_ptr; class vector; } 
namespace wil { class ActivityBase; class ActivityThreadWatcher; class CallContextInfo; class FailureInfo; class ResultException; class com_ptr_t; class err_exception_policy; class err_returncode_policy; class process_heap_deleter; class registry_watcher_t; class shared_any_t; class srwlock; class unique_any_t; } 
namespace wil { namespace details { class DestroyThreadPoolTimer; class FeatureLogging; class FeatureStateManager; class IFailureCallback; class ResultStatus; class StoredCallContextInfo; class SystemThreadPoolMethods; class ThreadFailureCallbackHolder; class delete_registry_watcher_state; class handle_null_resource_policy; class registry_watcher_state; class resource_policy; class shared_object; class shared_storage; class unique_storage; } } 
namespace wil { namespace details_abi { class FeatureStateData; class ProcessLocalData; class ProcessLocalStorageData; class RawUsageIndex; class ThreadLocalData; class UsageIndexProperty; class UsageIndexes; class heap_buffer; class heap_vector; } } 
namespace wistd { class default_delete; class function; class integral_constant; class unique_ptr; } 
namespace wistd { namespace __function { class __base; } } 

